version: '3.8'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: enterlife/yamdb_final:latest
    restart: always
    volumes:
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./static:/code/static
      - ./media:/code/media
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - web

volumes:
  postgres_data:
